resource_class: small
docker:
  - image: "cibuilds/base:<<parameters.tag>>"
    environment:
      TERM: dumb
parameters:
  tag:
    default: latest
    description: >
      Pick a specific cibuild/base image variant:
      https://hub.docker.com/r/cibuilds/base/tags
    type: string
